{{- if .Values.restore.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-mysql-restore
  {{- if .Values.restore.annotations.aws }}
  annotations:
    eks.amazonaws.com/role-arn: {{ toYaml .Values.restore.annotations.aws }}
  {{- end }}
{{- end }}
