{{- if .Values.backup.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-mysql-backup
  namespace: {{ .Release.Namespace }}
  annotations: 
    eks.amazonaws.com/role-arn: {{ .Values.backup.annotations }}
    
{{- end }}
