{{- if .Values.backup.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-mysql-backup
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ toYaml .Values.backup.annotations  | indent 4 }}
{{- end }}
